### PR TITLE
Update program-list.json

### PR DESCRIPTION
**Pull request by OppenheimersToy**
# Summary
Added info for Amazon, non-AWS

# Quality Assurance Checklist
< confirmation of this pull request meeting the following requirements, prior to merge >
| Review Items                            | Y/N |
|-----------------------------------------|-----|
| Site has a publicly known bug bounty    |  Y   |
| Disclosure terms are publicly available |  Y   |
| Public URL                              |   Y  |
| Single Source, or all sources appended  |  Y   |

### CODE REVIEW

**Review by yesnet0 — COMMENTED** [review]
Hi @OppenheimersToy - The links provided in `policy_url` and `submission_url` are specific to Amazon Retail Services, whilst the program name is for Amazon which would include Amazon AWS. Please choose a direction to take the update in (either updating the `program_name` and adding a new program for AWS, or reverting the `policy_url` and `submission_url`)

**Comment by OppenheimersToy** [comment]
Hi @yesnet0 

Apologies, perhaps the entries could then be more specific, as an "AWS" entry exists separately which is intentional as reports are not only handled by different parties, but have separate requirements. I'll edit and resubmit.

**Comment by OppenheimersToy** [comment]
I realized I never came back to this. What else needs to occur for this to be live on https://www.bugcrowd.com/bug-bounty-list/ now that AWS and Amazon have separate entries?

**Comment by yesnet0** [comment]
@OppenheimersToy You're probably best to contact your Bugcrowd account/support rep for that, disclose.io is a separate project - We've no control over how companies display the data we make available.

**Pull request merged**
